### ISSUE TITLE
Leaked Token

### ISSUE THREAD

**Issue by Incrility** [CookieBilly/MineplexSTM#2]
This is a public viewable project, ensure that all relevant tokens are removed!

https://github.com/CookieBilly/MineplexSTM/blob/0b8a3a0ca39cf4aadb221a6a86d377c71f44f43b/serviceAccountKey.json

Once you remove it delete the commit history to ensure people can’t see it

**Comment by isaackogan** [comment]
LOL

**Comment by xMdb** [comment]
nice tokens

**Comment by BillyDotWS** [comment]
Non issue, tokens don't hold anything of value (all migrated to a new account pre being made public)
